!e div content id="blog1"

# New Site
!var no_br=0
Before this, the site was just generated with Zine's default template, but I decided that it looked so boring I had to do something about it.

I got the idea to style the site after old Ubuntu, since i love the look of old GNOME.

I chose Ubuntu 10.04LTS Lucid Lynx for no particular reason, other than I saw it first and liked it. 

I wrote the site in two days, using [teg](https://paidbsd.org/teg), CSS, and a few lines of JS just to show the time on the top bar.

This does mean, that the website content renders and functions perfectly with JS disabled :3.

You can find the source code [here](https://github.com/aporvv/website)

!var no_br=99999
!e div content
