!e div window id="file"

!e div titlebar

!e div buttons
!e label close-btn for="hide"
![close](data/assets/close.png)
!e label close-btn
![max](data/assets/maximize.png)
![min](data/assets/minimize.png)
!e div buttons

!e div win_title
blog - File Browser
!e div win_title
!e div titlebar

!e div menubar
File Edit View Go Bookmarks Help
!e div menubar

!e div actionbar
![](data/assets/go-previous.svg)
!e div hide_on_mobile
Back
!e div hide_on_mobile
![](data/assets/dropdown-dark.svg)
![](data/assets/go-next.svg)
!e div hide_on_mobile
Forward
!e div hide_on_mobile
![](data/assets/dropdown-dark.svg)
![](data/assets/go-up.svg)
![](data/assets/process-stop.svg)
![](data/assets/view-refresh.svg)
!eoc img hide_on_mobile src="data/assets/separator.svg"
![](data/assets/user-home.svg)
![](data/assets/computer.svg)
!eoc img hide_on_mobile src="data/assets/separator.svg"
![](data/assets/zoom-out.svg)
!e div hide_on_mobile
100%
!e div hide_on_mobile
![](data/assets/zoom-in.svg)
!e div hide_on_mobile
!e div icon_view
!e div icon_view_text
Icon View
!e div icon_view_text
!e div icon_view_idk
!eoc img icon_view_drop src="data/assets/dropdown-dark.svg"
!e div icon_view_idk
!e div icon_view
!e div hide_on_mobile
![](data/assets/edit-find.svg)
!e div actionbar

!e div path-bar
!e div path-elem
![](data/assets/dark-arrow-left.svg)
!e div path-elem
!e div path-elem
![](data/assets/user-home.svg)
apor
!e div path-elem
!e div path-elem
![](data/assets/user-desktop.svg)
Desktop
!e div path-elem
!e div path-elem-final
blog
!e div path-elem-final
!e div path-bar

!e div files

!e div desktop_icon
!e a blog-link href="#blog1"
!e label trigger-label for="show_blog_gedit" aria-hidden="true" id="blog1-label"
![](data/assets/text-x-generic.svg)
!e label trigger-label
!e div
Blog 1
!e div
!e a blog-link
!e div desktop_icon

==!e div desktop_icon
==!e a blog-link href="#blog2"
==!e label trigger-label for="show_blog_gedit" aria-hidden="true" id="blog2-label"
==![](data/assets/text-x-generic.svg)
==!e label trigger-label
==!e div
==Blog 2
==!e div
==!e a blog-link
==!e div desktop_icon

!e div files

!e div file_infobar
1 Item, Free space: 62.1 GB
!e div file_infobar

!e div window
==!e div window_container
